development:
  adapter: postgresql
  encoding: unicode
  database: ntu_calendar_dev
  pool: 5
  username: Yulin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ntu_calendar_test
  pool: 5
  username: Yulin
  password:

